{
	"openapi": "3.0.3",
	"info": {
		"title": "Simple To Do List API (Golang)",
		"description": "API documentation of simple To Do list API.",
		"version": "1",
		"contact": {
			"name": "Ach Rozikin",
			"email": "geronimo794@gmail.com",
			"url": "https://rozik.in"
		},
		"license": {
			"name": "MIT"
		}
	},
	"servers": [
		{
			"url": "https://todoapi.rozik.in",
			"description": "Public Todo API Endpoint"
		},
		{
			"url": "http://localhost:3000",
			"description": "Local development API Endpoint"
		}
	],
	"externalDocs": {
		"description": "Blog Post Documentation of this Simple To Do List API",
		"url": "https://blog.rozik.in/open-api-simple-todo-list"
	},
	"paths": {
		"/login": {
			"post": {
				"tags": [
					"Authentification"
				],
				"description": "Get token bearer process",
				"requestBody": {
					"required": true,
					"content": {
						"multipart/form-data": {
							"schema": {
								"$ref": "#/components/schemas/inputAuth"
							},
							"examples": {
								"default": {
									"description": "Default auth",
									"value": {
										"username": "admin",
										"password": "admin"
									}
								}
							}
						}
					}
				},
				"responses": {
					"200": {
						"$ref": "#/components/responses/authSuccess"
					},
					"401": {
						"$ref": "#/components/responses/authFailed"
					}
				}
			}
		},
		"/register": {
			"post": {
				"tags": [
					"Authentification"
				],
				"description": "Register username to get auth token",
				"requestBody": {
					"required": true,
					"content": {
						"multipart/form-data": {
							"schema": {
								"$ref": "#/components/schemas/inputAuth"
							},
							"examples": {
								"default": {
									"description": "Default auth",
									"value": {
										"username": "admin",
										"password": "admin"
									}
								}
							}
						}
					}
				},
				"responses": {
					"200": {
						"$ref": "#/components/responses/authSuccess"
					},
					"403": {
						"$ref": "#/components/responses/registerFailed"
					}
				}
			}
		},
		"/todo": {
			"get": {
				"security": [
					{
						"bearerAuth": []
					}
				],
				"tags": [
					"Get Data"
				],
				"summary": "Get todo list data",
				"description": "Get all todo list data with simple filter operation",
				"parameters": [
					{
						"$ref": "#/components/parameters/isDone"
					},
					{
						"$ref": "#/components/parameters/keyword"
					}
				],
				"responses": {
					"200": {
						"description": "Success get todo list data",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/responseTodoListData"
								},
								"examples": {
									"success": {
										"$ref": "#/components/examples/responseTodoList200"
									}
								}
							}
						}
					},
					"404": {
						"$ref": "#/components/responses/dataNotFound"
					},
					"400": {
						"$ref": "#/components/responses/emptyOrWrongJWT"
					}
				}
			},
			"post": {
				"security": [
					{
						"bearerAuth": []
					}
				],
				"tags": [
					"Create Data"
				],
				"summary": "Create todo data",
				"description": "Create todo list data",
				"requestBody": {
					"required": true,
					"content": {
						"multipart/form-data": {
							"schema": {
								"$ref": "#/components/schemas/inputTodo"
							},
							"examples": {
								"kerja": {
									"description": "Example create to do data with kerja",
									"value": {
										"name": "Mengerjakan servers dan migrasi data pengguna",
										"priority": "high"
									}
								},
								"belanja": {
									"description": "Example create to do data with belanja",
									"value": {
										"name": "Belanja makanan bulanan",
										"priority": "medium"
									}
								}
							}
						}
					}
				},
				"responses": {
					"200": {
						"$ref": "#/components/responses/singleData"
					},
					"400": {
						"$ref": "#/components/responses/emptyOrWrongJWT"
					}
				}
			}
		},
		"/todo/{id}": {
			"get": {
				"security": [
					{
						"bearerAuth": []
					}
				],
				"tags": [
					"Get Data"
				],
				"summary": "Get todo data",
				"description": "Get single todo list data by spesific Id",
				"parameters": [
					{
						"$ref": "#/components/parameters/id"
					}
				],
				"responses": {
					"200": {
						"$ref": "#/components/responses/singleData"
					},
					"404": {
						"$ref": "#/components/responses/dataNotFound"
					},
					"400": {
						"$ref": "#/components/responses/emptyOrWrongJWT"
					}
				}
			},
			"delete": {
				"security": [
					{
						"bearerAuth": []
					}
				],
				"tags": [
					"Delete Data"
				],
				"summary": "Delete todo data",
				"description": "Delete single todo list data",
				"parameters": [
					{
						"$ref": "#/components/parameters/id"
					}
				],
				"responses": {
					"200": {
						"$ref": "#/components/responses/singleData"
					},
					"404": {
						"$ref": "#/components/responses/dataNotFound"
					},
					"400": {
						"$ref": "#/components/responses/emptyOrWrongJWT"
					}
				}
			},
			"put": {
				"security": [
					{
						"bearerAuth": []
					}
				],
				"tags": [
					"Modify Data"
				],
				"summary": "Edit todo data",
				"description": "Edit text of todo data",
				"parameters": [
					{
						"$ref": "#/components/parameters/id"
					}
				],
				"requestBody": {
					"required": true,
					"content": {
						"multipart/form-data": {
							"schema": {
								"$ref": "#/components/schemas/inputTodo"
							},
							"examples": {
								"kerja": {
									"description": "Example create to do data with kerja",
									"value": {
										"name": "Mengerjakan servers dan migrasi data pengguna",
										"priority": "high"
									}
								},
								"belanja": {
									"description": "Example create to do data with belanja",
									"value": {
										"name": "Belanja makanan bulanan",
										"priority": "medium"
									}
								}
							}
						}
					}
				},
				"responses": {
					"200": {
						"$ref": "#/components/responses/singleData"
					},
					"404": {
						"$ref": "#/components/responses/dataNotFound"
					},
					"400": {
						"$ref": "#/components/responses/emptyOrWrongJWT"
					}
				}
			}
		},
		"/todo/{id}/reverse-status": {
			"put": {
				"security": [
					{
						"bearerAuth": []
					}
				],
				"tags": [
					"Modify Data"
				],
				"summary": "Reverse the status of the todo data",
				"description": "Change status of the todo data. If status 1 it will be 0, if status 0 it will be 1.",
				"parameters": [
					{
						"$ref": "#/components/parameters/id"
					}
				],
				"responses": {
					"200": {
						"$ref": "#/components/responses/singleData"
					},
					"404": {
						"$ref": "#/components/responses/dataNotFound"
					},
					"400": {
						"$ref": "#/components/responses/emptyOrWrongJWT"
					}
				}
			}
		}
	},
	"components": {
		"securitySchemes": {
			"bearerAuth": {
				"type": "http",
				"scheme": "bearer",
				"bearerFormat": "JWT",
				"description": "Every action on this API need JWT token to be authorize"
			}
		},
		"parameters": {
			"id": {
				"name": "id",
				"description": "Primary key identifier of main data",
				"in": "path",
				"required": true,
				"schema": {
					"type": "integer",
					"nullable": false,
					"minimum": 1,
					"maximum": 1000000000,
					"format": "int64",
					"maxLength": 100
				}
			},
			"isDone": {
				"name": "isDone",
				"description": "Additional parameter to get the is_done status of the todo data",
				"in": "query",
				"required": false,
				"allowEmptyValue": true,
				"schema": {
					"type": "boolean",
					"nullable": true
				}
			},
			"keyword": {
				"name": "keyword",
				"description": "General input keyword for searching",
				"in": "query",
				"required": false,
				"schema": {
					"type": "string",
					"nullable": true,
					"minLength": 3,
					"maxLength": 100
				},
				"examples": {
					"belanja": {
						"value": "belanja",
						"description": "Example find to do data have keyword belanja"
					},
					"kerja": {
						"value": "kerja",
						"description": "Example find to do data have keyword kerja"
					}
				}
			}
		},
		"schemas": {
			"todo": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"id": {
						"type": "integer"
					},
					"name": {
						"type": "string",
						"nullable": false,
						"minLength": 1
					},
					"priority": {
						"type": "string",
						"enum": [
							"low",
							"medium",
							"high"
						],
						"nullable": false
					},
					"is_done": {
						"type": "boolean",
						"description": "The is_done status of the todo data",
						"nullable": false
					}
				}
			},
			"inputTodo": {
				"type": "object",
				"additionalProperties": false,
				"required": [
					"name",
					"priority"
				],
				"properties": {
					"name": {
						"type": "string",
						"minLength": 3,
						"maxLength": 100,
						"nullable": false,
						"example": "Belanja makanan bulanan"
					},
					"priority": {
						"type": "string",
						"enum": [
							"low",
							"medium",
							"high"
						],
						"default": "low",
						"nullable": false
					}
				}
			},
			"inputAuth": {
				"type": "object",
				"additionalProperties": false,
				"required": [
					"username",
					"password"
				],
				"properties": {
					"username": {
						"type": "string",
						"nullable": false,
						"example": "admin"
					},
					"password": {
						"type": "string",
						"nullable": false,
						"example": "admin"
					}
				}
			},
			"responseNotFound": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"code": {
						"type": "integer",
						"example": 200
					},
					"message": {
						"type": "string",
						"example": "OK"
					},
					"data": {
						"type": "object",
						"nullable": true
					},
					"errors": {
						"type": "object",
						"nullable": true
					}
				}
			},
			"responseTodo": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"code": {
						"type": "integer",
						"example": 200
					},
					"message": {
						"type": "string",
						"example": "OK"
					},
					"data": {
						"$ref": "#/components/schemas/todo"
					},
					"errors": {
						"type": "object",
						"nullable": true
					}
				}
			},
			"responseTodoListData": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"code": {
						"type": "integer",
						"example": 200
					},
					"message": {
						"type": "string",
						"example": "OK"
					},
					"data": {
						"type": "array",
						"nullable": true,
						"items": {
							"$ref": "#/components/schemas/todo"
						}
					},
					"errors": {
						"type": "object",
						"nullable": true
					}
				}
			},
			"responseAuthSuccess": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"code": {
						"type": "integer",
						"example": 200
					},
					"message": {
						"type": "string",
						"example": "OK"
					},
					"data": {
						"type": "object",
						"nullable": false,
						"properties": {
							"token": {
								"type": "string",
								"example": "aaa.bbb.ccc"
							}
						}
					},
					"errors": {
						"type": "object",
						"nullable": true
					}
				}
			},
			"responseRegisterFailed": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"code": {
						"type": "integer",
						"example": 409
					},
					"message": {
						"type": "string",
						"example": "Conflict"
					},
					"data": {
						"type": "object",
						"nullable": true,
						"example": null
					},
					"errors": {
						"type": "array",
						"nullable": true,
						"items": {
							"type": "object",
							"properties": {
								"title": {
									"type": "string"
								},
								"message": {
									"type": "array",
									"items": {
										"type": "string"
									}
								}
							}
						}
					}
				}
			},
			"responseAuthFailed": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"code": {
						"type": "integer",
						"example": 401
					},
					"message": {
						"type": "string",
						"example": "Unauthorized"
					},
					"data": {
						"type": "object",
						"nullable": true,
						"example": null
					},
					"errors": {
						"type": "object",
						"nullable": true,
						"example": null
					}
				}
			},
			"responseMessageOnly": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"message": {
						"type": "string",
						"example": "missing or malformed jwt"
					}
				}
			}
		},
		"examples": {
			"response400": {
				"description": "Invalid JWT Token",
				"value": {
					"message": "missing or malformed jwt"
				}
			},
			"responseAuth401": {
				"description": "When authentification failed",
				"value": {
					"code": 401,
					"message": "Unauthorized",
					"data": null,
					"errors": null
				}
			},
			"response404": {
				"description": "Response data if data not available or not found",
				"value": {
					"code": 404,
					"message": "Not Found",
					"data": null,
					"errors": null
				}
			},
			"responseTodoSingle200": {
				"description": "Example of single response data",
				"value": {
					"code": 200,
					"message": "OK",
					"data": {
						"id": 1,
						"name": "Mengerjakan PR",
						"priority": "low",
						"status": 1
					}
				}
			},
			"responseTodoList200": {
				"description": "Example of list response data",
				"value": {
					"code": 200,
					"message": "OK",
					"data": [
						{
							"id": 1,
							"name": "Mengerjakan PR",
							"priority": "low",
							"status": 1
						},
						{
							"id": 2,
							"name": "Mengerjakan PR",
							"priority": "low",
							"status": 1
						}
					]
				}
			},
			"responseAuth200": {
				"description": "Example of list response data",
				"value": {
					"code": 200,
					"message": "OK",
					"data": {
						"token": "aaa.bbb.ccc"
					},
					"errors": null
				}
			},
			"responseRegister403": {
				"description": "Example of failed register",
				"value": {
					"code": 409,
					"message": "Conflict",
					"data": null,
					"errors": [
						{
							"title": "username",
							"messages": [
								"is already exist"
							]
						}
					]
				}
			}
		},
		"responses": {
			"singleData": {
				"description": "Response data for single data operation",
				"content": {
					"application/json": {
						"schema": {
							"$ref": "#/components/schemas/responseTodo"
						},
						"examples": {
							"success": {
								"$ref": "#/components/examples/responseTodoSingle200"
							}
						}
					}
				}
			},
			"authSuccess": {
				"description": "Response data for success authentification process",
				"content": {
					"application/json": {
						"schema": {
							"$ref": "#/components/schemas/responseAuthSuccess"
						},
						"examples": {
							"success": {
								"$ref": "#/components/examples/responseAuth200"
							}
						}
					}
				}
			},
			"registerFailed": {
				"description": "Response data if registration failed",
				"content": {
					"application/json": {
						"schema": {
							"$ref": "#/components/schemas/responseRegisterFailed"
						},
						"examples": {
							"success": {
								"$ref": "#/components/examples/responseRegister403"
							}
						}
					}
				}
			},
			"authFailed": {
				"description": "Response if authentification process failed",
				"content": {
					"application/json": {
						"schema": {
							"$ref": "#/components/schemas/responseAuthFailed"
						},
						"examples": {
							"success": {
								"$ref": "#/components/examples/responseAuth401"
							}
						}
					}
				}
			},
			"dataNotFound": {
				"description": "Response if the operation data not found",
				"content": {
					"application/json": {
						"schema": {
							"$ref": "#/components/schemas/responseNotFound"
						},
						"examples": {
							"success": {
								"$ref": "#/components/examples/response404"
							}
						}
					}
				}
			},
			"emptyOrWrongJWT": {
				"description": "Response if your JWT token not valid",
				"content": {
					"application/json": {
						"schema": {
							"$ref": "#/components/schemas/responseMessageOnly"
						},
						"examples": {
							"success": {
								"$ref": "#/components/examples/response400"
							}
						}
					}
				}
			}
		}
	}
}